# .github/workflows/check-license.yml

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'CHECK - License Boilerplate'

on:
  schedule:
    - cron:  '*/30 * * * *' 
  workflow_dispatch:
    inputs:
          PRNumber:
            description: 'PR #'     
            required: true
permissions:
  issues: write
  pull-requests: write

jobs:
  license:
    name: 'Files with no License'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: tools

      - name: execute py script (scheduled) # run the check-license.py
        id: boilerplate-scheduled
        if: github.event_name == 'schedule'
        run: |
          python check-license.py
        working-directory: tools

      - name: execute py script (manual) # run the check-license.py
        id: boilerplate-manual
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [[ "${{ github.event.inputs.PRNumber }}" =~ ^[0-9]+$ ]] || [[ "${{ github.event.inputs.PRNumber }}" == "All" ]]
          then
            python check-license.py ${{ github.event.inputs.PRNumber }}
          else
            echo "INVALID PR Number ENTERED..."
            exit 1
          fi
        working-directory: tools